### ISSUE TITLE
Code Review for Lee Yi Min

### ISSUE THREAD

**Issue by OuyangDanwen** [CS2103AUG2016-W10-C1/main#103]
Code quality for both test code and main code are okay. Test cases are namely correctly. Remember to have some comments for tests and non-trivial methods. @leeyimin

**Comment by leeyimin** [comment]
@OuyangDanwen Thanks for the review! I would like to clarify what you meant in the first sentence.

**Comment by OuyangDanwen** [comment]
@leeyimin Sorry for the typo. I have changed it accordingly.
