### ISSUE TITLE
Code Review for Alex Fong Jie Wen

### ISSUE THREAD

**Issue by OuyangDanwen** [CS2103AUG2016-W10-C1/main#104]
For code in main, comments should be phrased more formally. For example, "use may have forgotten..." should change to "Handle the case when user....". There are missing comments here and there. Comments should be given for all non-trivial methods, especially when the logic is complex. The second constructor for Schedule is one of the places where you can add more comments to explain the logic, or better refactor it, as it is a bit too long. For test code, you should  test all  cases of failure and check the corresponding error message (missing timezone error).  Also, more comments needed here. Lastly, remember to remove all TODO items for the actual review. @AlexFJW

**Comment by alexfjw** [comment]
Sure. Will work on that. Thanks for the review.
