### ISSUE TITLE
Code Review for Inaba Kazuhiro

### ISSUE THREAD

**Issue by OuyangDanwen** [CS2103AUG2016-W10-C1/main#105]
For test code, tests are named correctly. May want to add more comments for tests. Some tests are ignored, which should not appear for the actual review. For code in main, you have noticed that SLAP can applied across your implementations of panels to extract the common code. Same issue for comments here. TODO items should be removed for the actual review. @inaba1231

**Comment by kazuhiroinaba** [comment]
Oh okay, thank you for the review!
