### ISSUE TITLE
Code cleanup for final release

### ISSUE THREAD

**Issue by jia1** [CS2103AUG2016-W10-C1/main#125]
- [x] Remove all unused code
- [x] Add feedback message for list command
- [x] Fix feedback message for select command
- [x] Beautify feedback message for select command
- [x] Fix toString methods in Deadline and Schedule
- [x] Separate formatting from parsing
- [x] Continue cleaning up Schedule file (method body is repetitive and some format strings are still around)
- [x] Move all magic numbers/strings to the top of the file (or out of the file)
- [x] Check if unused methods are really unneeded
- [x] Deal with all //TODO
- [x] Clean up tests

**Comment by alexfjw** [comment]
Did some of the cleaning up for Schedule. Didn't touch the format strings though. Only renamed some of them for clarity.

Not particularly fond of format strings, as the compiler isn't able to help us if format strings are misused / used in the wrong place.

**Comment by jia1** [comment]
Okay
