### ISSUE TITLE
Currently, nothing occurs when schedules are over

### ISSUE THREAD

**Issue by kazuhiroinaba** [CS2103AUG2016-W10-C1/main#130]

**Comment by jia1** [comment]
I failed.

Branch [fail/refresh/schedule](https://github.com/CS2103AUG2016-W10-C1/main/tree/fail/refresh/schedule)

I tried the following:

> Add a timer to run a function every second (delete from the schedule list + refresh GUI), dk where to add the timer and dk where to update the list.

Did not try the following:

> Write to the storage file every second (sounds time-consuming).

**Comment by alexfjw** [comment]
Did some of this with #137.
Currently only works when loading data.

Periodic filtering / checking will be added for the next milestone.
-> probably going to use a separate thread which sleeps for a long duration

**Comment by jia1** [comment]
Yes Sir.

**Comment by alexfjw** [comment]
Leaving this as it is, since users are unlikely to expect tasks disappearing on their own as they use the app.
