### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by kazuhiroinaba** [CS2103AUG2016-W10-C1/main#133]
- Rather than list, it became more of a search command.
- Searching on a filtered list, does not go back to original list first.
- Search by tags does not work on all panels

**Comment by leeyimin** [comment]
Should list be renamed?

I cannot replicate the second problem as well. Is it already fixed?

**Comment by kazuhiroinaba** [comment]
hmm, actually renaming it sounds troublesome, I think we just leave it :p
yeah second problem seems fixed on my side as well.
