### ISSUE TITLE
Response messages for timings

### ISSUE THREAD

**Issue by alexfjw** [CS2103AUG2016-W10-C1/main#152]
Do you think changing "moments" to "some seconds" will help with readability? @jia1 
The thought just occurred to me but I suppose it could be just me being unfamiliar with the terminology.
 
Output in console after adding a Task:

Schedule:
	Sun, 06 Nov 16, 8.19PM (moments ago)

vs

Schedule:
	Sun, 06 Nov 16, 8.19PM (some seconds ago)

**Comment by jia1** [comment]
No difference to me, imo. What do the rest think?

**Comment by alexfjw** [comment]
Hmm if that's the case we'll skip this then. Thanks for the input.
