### ISSUE TITLE
Changes to CodeStyle

### ISSUE THREAD

**Issue by alexfjw** [CS2103AUG2016-W10-C1/main#16]
Issue to track changes in codestyle
- keep switch cases in braces 
- use non-capturing groups for regex (?:X) , where X is the regex
  (to easily reference groups, without using named capturing groups -> very clunky)

**Comment by alexfjw** [comment]
note areas which may affect UG/DG by adding a comment of the following format in code:
- // UG/DG

**Comment by jia1** [comment]
You can use capturing groups to organize and parse an expression. A non-capturing group has the first benefit, but doesn't have the overhead of the second. You can still say a non-capturing group is optional, for example.

Say you want to match numeric text, but some numbers could be written as 1st, 2nd, 3rd, 4th,... If you want to capture the numeric part, but not the (optional) suffix you can use a non-capturing group.

([0-9]+)(?:st|nd|rd|th)?
That will match numbers in the form 1, 2, 3... or in the form 1st, 2nd, 3rd,... but it will only capture the numeric part.

[Source](http://stackoverflow.com/questions/3512471/what-is-a-non-capturing-group)

**Comment by alexfjw** [comment]
Convention for test naming. Focus on what the test is doing, rather than the name of the method tested.
http://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html

Examples at XmLTaskManStorage.java & XmlTaskManStorageTest.java

**Comment by alexfjw** [comment]
I'd like to standardize capitalization for test naming as well.
Treat each part of the name as a separate word, and stick to camelcase for words.

Eg: a test which adds a single task 
add_singleTask_success() { ... }

-> press caps less. yay!

**Comment by alexfjw** [comment]
Try not to use abbreviations if possible.

Example:
The original addressbook app calls an AddressBook member variable ab in one of the base classes for tests. Would be better if it were called addressBook. 

Makes refactoring easier & I think its much clearer for people who are looking at the code for the first time.

**Comment by jia1** [comment]
Yes madam
