### ISSUE TITLE
Resolve tests

### ISSUE THREAD

**Issue by kazuhiroinaba** [CS2103AUG2016-W10-C1/main#21]

**Comment by alexfjw** [comment]
I'll take all those related to Add.

**Comment by alexfjw** [comment]
Remaining tests to fix
-> edit
-> list (some tests fail occasionally. Could be a bug with the Tag generation code. 
-> UI tests

**Comment by jia1** [comment]
What's this? Test for EditCommand is it?

Ya the test for list command breaks randomly.
