### ISSUE TITLE
Descriptive toString() representations for Data Objects

### ISSUE THREAD

**Issue by jia1** [CS2103AUG2016-W10-C1/main#22]

**Comment by alexfjw** [comment]
http://www.ocpsoft.org/prettytime/ 

Looks pretty cool, quoting a code sample from the site:

PrettyTime p = new PrettyTime(); 
System.out.println(p.format(new Date()));
//prints: “moments from now”

System.out.println(p.format(new Date(System.currentTimeMillis() + 1000_60_10)));
//prints: “10 minutes from now”

Already approved on the CS2103 forum.

**Comment by alexfjw** [comment]
But I wonder if the app works realtime. 
I'm guessing it doesn't, so we'll have to fix that if we want to use a relative time display like this one. Going to be messy if there are 5 mins left, and yet the display doesn't update after 5 mins. Also I think it'll be good to show both the exact & the relative deadline (separated by \n?). 

Doesn't feel like a high priority item.
We should get input from the rest before deciding whether to use this, or implement at this point.

**Comment by jia1** [comment]
Don't worry about refreshing. That should be nice-to-have!

**Comment by alexfjw** [comment]
@leeyimin, @inaba1231 

Regarding storing what the user put in & returning it as the toString representation. 
Could you remind me of the motivations behind this? 

I feel that it might be confusing as there's a lot of ways the user can express the datetime. 
Even 'two Wednesdays from now' works and that might lead to complications.

**Comment by leeyimin** [comment]
Was referring specifically to frequency actually. We can just store and return the string that was used to construct the field.

**Comment by alexfjw** [comment]
Ah right. Would make sense in that case, since we already fix what can be
entered by the user using the regex.

**Comment by jia1** [comment]
I'm confused about this discussion, but from what I know, and in response to:

> Regarding storing what the user put in & returning it as the toString representation. 
> Could you remind me of the motivations behind this?
1. User input should be parsed and stored as an absolute date (if not next Friday will forever remain as next Friday)
2. toString makes PrettyTime format the date on the fly so that it is real-time

There may be some redundant functions around but I don't feel like poking them unless I have to...

**Comment by alexfjw** [comment]
@jia1  Fix-commmited? -> make PR

**Comment by jia1** [comment]
@AlexFJW yeah bro I just did, thanks!
