### ISSUE TITLE
Implement Undo

### ISSUE THREAD

**Issue by kazuhiroinaba** [CS2103AUG2016-W10-C1/main#34]
Implement undo function
- [x] HistoryCommand
- [x] HistoryCommand Tests (omg... T_T)
- [x] UndoCommand
- [x] UndoCommand Tests (omg... T_T)

Decisions:
1. Store commands in memory, store where in Command class
2. It does not make sense to store "delete 1" only (the user can't remember what's 1) since "list ..." would have escaped the command history. Why not just include "list..." first?
3. Do Cloning interface stuff
4. Other ways to implement: Each command history stores the Command object with undo() and Command input string in memory (delete 1 -> delete <task title> for understandability)

**Comment by alexfjw** [comment]
Rough workplan for undo 

Get backend code working 
1) commands to store snapshots of database (before & after) 
2) taskman to store stack of commands 

Add history command 

Add undo command

**Comment by alexfjw** [comment]
@jia1 
Could you share your implementation plan here? Thanks

**Comment by jia1** [comment]
**UPDATE**: NOW CAN MERGE for new/command/history (:

new/command/undo branches from new/command/history

Two deques:
1. One for input strings (for the history command, already implemented, but right now accepts all commands excluding history itself)
2. The other for the Clone thing (have not researched into it) Why clone thing? Because it's open to extension and close to modification

**Comment by kazuhiroinaba** [comment]
hi, how can we help? Not familiar with the status of this issue.

**Comment by jia1** [comment]
The files are written when undo is called, but the files get written to its current state (as good as nothing is written)

Even though the deque was popping correctly

So I'm not sure whether the TaskMan I pushed is wrong, or the resetData procedure is wrong, or some other error

**Comment by alexfjw** [comment]
Took over your work & did some cleaning up. No errors after the cleanup so all is good. Good job btw! (I changed the architecture of undo but your work helped me save a lot of time)
