### ISSUE TITLE
Sort command

### ISSUE THREAD

**Issue by jia1** [CS2103AUG2016-W10-C1/main#47]
Sort by deadline and stuff like that

**Comment by leeyimin** [comment]
Current plan:
- [ ] Implement ActivityComparator
- put related enum in seedu....model.event.sort package 
- [ ] Implement sorting in ModelManager 
- allows sorting after list command etc
- [ ] Implement SortCommand
- [ ] Implement in CommandParser

**Comment by kazuhiroinaba** [comment]
Sort is mostly done on my branch
