### ISSUE TITLE
Include "delete all" command

### ISSUE THREAD

**Issue by jia1** [CS2103AUG2016-W10-C1/main#48]
Right now there is only "delete 1". Why not just morph "ClearCommand" into "DeleteListCommand".

Things to note if morphing: Must put DeleteListCommand.COMMAND_WORD above DeleteCommand.COMMAND_WORD in switch-case and break.

**UPDATE (SUNDAY)**
1. delete and clear are different. clear resets the entire file. clear should be renamed to reset.
2. delete all is a condition in delete, and all -> index 0 in DeleteCommand.java
3. delete all needs help with parsing because current parsing is hard-coded.

Test fails because of assertion error, don't know how to fix, see PR

**Comment by jia1** [comment]
See above

**Comment by alexfjw** [comment]
Differed till further notice (not high priority)
