### ISSUE TITLE
CRUD support Event and Task

### ISSUE THREAD

**Issue by kazuhiroinaba** [CS2103AUG2016-W10-C1/main#58]
- [x] Edit does not retain tags of the activity.
- [x] Complete does not support Event.
- [x] Complete does not support Activity with null fields.
- [x] C and U currently allows Activities with duplicate titles.
- [x] Task with status 'complete' does not load

**Comment by jia1** [comment]
Wait why do you need to complete an event?

**Comment by kazuhiroinaba** [comment]
Instead of needing to complete an event, there must be some deterrence to completing an event.

By the way, is complete buggy on your side? It runs into an error depending on the index I choose.
