### ISSUE TITLE
Observations from Dogfooding 

### ISSUE THREAD

**Issue by alexfjw** [CS2103AUG2016-W10-C1/main#69]
Update this list when you find something:

Editing task name may result in the task being re-ordered
-> highlight tasks added to TaskMan?

**Comment by leeyimin** [comment]
- wrap text for ResultDisplay text area 
- focus on CommandBox textfield on some keyboard input

**Comment by jia1** [comment]
In the task box, if the words go beyond the column, they are truncated by ...

Remove all scrollbarring

**Comment by alexfjw** [comment]
-> storageloc's relative location parsing feels a little unusual.

> storageloc ./fishcake
> Should give relative location of (relative)/fishcake
> Currently gives (relative)/./fishcake

-> using list feels a little unusual (not sure how to fix)

> list d     -> list tasks with d in the name
> list d/    -> list tasks with deadlines
