### ISSUE TITLE
Remove select feature

### ISSUE THREAD

**Issue by jia1** [CS2103AUG2016-W10-C1/main#72]
Please state any objections here

**Comment by jonodonovan** [comment]
> Remove select feature

What do you mean by this?

**Comment by jia1** [comment]
@jonodonovan It's a clean-up of features we do not want from the original source code.

**Comment by leeyimin** [comment]
select is useful now due as only certain information are displayed on table and select shows all fields of the activity selected

**Comment by jia1** [comment]
Yeah! Realised it yesterday, thanks!
