### ISSUE TITLE
Fix bad number parsing

### ISSUE THREAD

**Issue by jia1** [CS2103AUG2016-W10-C1/main#73]
Because undo accepts empty argument, bad numbers will become 0 in the eyes of undo

**Comment by z4f1r0v** [comment]
@jia1 Can you provide a link to the exact file? I browsed through the repo and couldn't find anything with the name _Undo_.

**Comment by jia1** [comment]
@alexanderzafirov It's still being worked on a different branch. [Here you go.](https://github.com/CS2103AUG2016-W10-C1/main/blob/new/command/undo/src/main/java/seedu/taskman/logic/commands/UndoCommand.java)
