### ISSUE TITLE
Cleanup/ standardize command Messages

### ISSUE THREAD

**Issue by alexfjw** [CS2103AUG2016-W10-C1/main#82]
Response messages for commands aren't exactly that tidy right now. 
Might be good to relocate them all into one file, so it's easy to stick to the same style.

Might be good to restore message checking for tests at the same time.
(previously removed to simplify testing)

**Comment by jia1** [comment]
@AlexFJW every single literal (magic number, string) goes to

src/main/java/seedu/taskman/commons/core/Messages.java

?

**Comment by alexfjw** [comment]
No only messages to show up in ui.
Error messages, recommended inputs etc
